name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Nginx
      run: |
        sudo apt-get update
        sudo apt-get install nginx
        sudo systemctl start nginx

    - name: Deploy to Nginx
      run: |
        sudo cp -r * /var/www/html/
        sudo systemctl restart nginx
